### ISSUE TITLE
Few comments

### ISSUE THREAD

**Issue by Neargye** [felixguendling/nameof#1]
1. `NAMEOF(test::SomeMethod3()) -> "SomeMethod3"` not ` "test::SomeMethod3"`, because the nameof operator removes the namespace frome name.

2. If you change `constexpr std::string_view nameof_type_impl()` -> `std::string_view nameof_type_impl()` cahnge also  `"constexpr std::string_view nameof::detail::nameof_type_impl() [with "`  -> `"std::string_view nameof::detail::nameof_type_impl() [with "`

3. 
```cpp
namespace test {
struct Long {
  struct LL {
    int field = 0;
  };
  LL ll;
};
}
test::Long othervar;
```
`NAMEOF_TYPE(othervar.ll)` -> test::Long::LL` , because the nameof_type operator saves the namespace frome type name.

**Comment by felixguendling** [comment]
Thank you!

I aim to use your approach to compute a version hash for data structures for my serialization library Cista++ (https://github.com/felixguendling/cista). For this, I need the namespace (as you mentioned). But additionally, I would like to have similar outputs for each supported platform/compiler (MSVC, GCC, Clang). Therefore, I implemented a version with a function to canonicalize the names. Since GCC and Clang deliver the same output for the types I have tested, I decided to use this as the "canonical" form. Thus, I wrote a function to transform the MSVC output to match the GCC/Clang output.

That's my basic version:
https://github.com/felixguendling/cista/blob/28eb7933c2c71fae3a29658601104d32b8f82d66/include/cista/type_hash/type_name.h#L36-L58

And this is the code to transform the MSVC output to match the Clang/GCC output. I think it needs to be extended for anonymous namespaces:
https://github.com/felixguendling/cista/blob/28eb7933c2c71fae3a29658601104d32b8f82d66/include/cista/type_hash/type_name.h#L13-L28

Finally, I hash those type name strings to generate a version ID for each serialized data structure (recursively):
https://github.com/felixguendling/cista/blob/28eb7933c2c71fae3a29658601104d32b8f82d66/include/cista/type_hash/hash.h#L11-L25

That's the recursive part (iterating over each aggregate field):
https://github.com/felixguendling/cista/blob/28eb7933c2c71fae3a29658601104d32b8f82d66/include/cista/type_hash/type_hash.h#L22-L41

Feel free to look into those implementations and give feedback :)

**Comment by felixguendling** [comment]
I see, you also remove the 'struct' for MSVC at the beginning:
https://github.com/Neargye/nameof/blob/master/include/nameof.hpp#L145-L155

**Comment by Neargye** [comment]
If you need type inference in one format for all compilers, then I would suggest
1.  removes all const, volatile, reference, pointer, array extents specifiers from the given type. [Like](https://github.com/Neargye/yacppl/blob/2487583551712960b3dad92b4668c369ee1ac7db/include/nstd.hpp#L72)
So on all comtiler you get `NAMEOF_TYPE(std::declval<const SomeClass<int>>()) -> "SomeClass<int>"`
not `NAMEOF_TYPE(std::declval<const SomeClass<int>>()) == "const SomeClass<int> &&"`
2. Then check if type const and add "const", etc.

**Comment by Neargye** [comment]
> I see, you also remove the 'struct' for MSVC at the beginning:
> https://github.com/Neargye/nameof/blob/master/include/nameof.hpp#L145-L155
> 
> The problem is with types that have it somewhere in the middle of the string:
> e.g. `std::string<my_struct_name>`.

For this i use wrap `identity` see https://github.com/Neargye/nameof/blob/696d84ecc6f0cc39e8f62e14de0307a5ebb25906/include/nameof.hpp#L264

**Comment by Neargye** [comment]
> > I see, you also remove the 'struct' for MSVC at the beginning:
> > https://github.com/Neargye/nameof/blob/master/include/nameof.hpp#L145-L155
> > The problem is with types that have it somewhere in the middle of the string:
> > e.g. `std::string<my_struct_name>`.
> 
> For this i use wrap `identity` see https://github.com/Neargye/nameof/blob/696d84ecc6f0cc39e8f62e14de0307a5ebb25906/include/nameof.hpp#L264

although it doesn't work with nested structures,  need to think.

**Comment by Neargye** [comment]
> I see, you also remove the 'struct' for MSVC at the beginning:
> https://github.com/Neargye/nameof/blob/master/include/nameof.hpp#L145-L155
> 
> The problem is with types that have it somewhere in the middle of the string:
> e.g. `std::vector<my_struct_name>`.

For this i use wrap `identity` see https://github.com/Neargye/nameof/blob/696d84ecc6f0cc39e8f62e14de0307a5ebb25906/include/nameof.hpp#L264

Then you can clear name remove 'class/struct': `class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >` -> `std::basic_string<char, std::char_traits<char>,std::allocator<char> >`

I’ll remove all spaces to be sure of portability
`std::basic_string<char, std::char_traits<char>,class std::allocator<char> >` -> `std::basic_string<char, std::char_traits<char>,std::allocator<char>>`

**Comment by Neargye** [comment]
Portability Gcc/Clang:
Case 1
```cpp
template <typename... T>
[[nodiscard]] constexpr std::string_view nameof_type_impl() noexcept {
```
nameof_type_impl<std::string>() -> std::__cxx11::basic_string<char>

Case 2 (add variadic template)
template <typename... T>cpp
[[nodiscard]] constexpr std::string_view nameof_type_impl() noexcept {
```
nameof_type_impl<std::string>() -> std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >

**Comment by Neargye** [comment]
So to Portability Gcc/Clang<-> MSVC
1. Need use variadic template to add full type name
2. Replace `std::__cxx11` to `std`

**Comment by Neargye** [comment]
I hope these comments will help you. If you need help with your library, please contact me.
